### ISSUE TITLE
[Question] - motivation to move Gatsby?

### ISSUE THREAD

**Issue by nsisodiya** [mhjadav/wordpress-blog-gatsby#1]
Nice blog - I am mostly curious about the main motivation to move Gatsby?
we want to move one wordpress site to Gatsby but efforts are mostly high.
1. Only advantage I can see - Static website. I guess, in wordpress, we need to run Server.

**Comment by mhjadav** [comment]
Hey @nsisodiya,

Thanks

Very sorry for the late reply, was not very active so missed your message.

Do still need any clarification?

If Yes here are some point that may help you -

1. Static site - In both case you need some server to run your web site, by static mean your content is already generated when you build your site rather then fetching run time. so gatsby help you to do that. When you build your site gatsby fetches content from any CDN, put it in graphql schema and that you can use to generate pages as you which. because of this you will get faster and efficient web page 
2. Other then this feature gatsby team work on many other things like gatsby plugins for images and other such use case
Let's take example for image image plugin are so usefull to optimize image of any resolution and also with lazy loading which result in better web ppage
3. Other plugin to convert your web app to PWA by just addiing one plugin
4. Other plugin like manifest, robots, file system, transform json etc. this plugin help you build better web app in many way.
I am not adding detail here but you can find very good description on gatsby docs.
4. Other feature like gatsby theme, 0 config build

Gatsby is very well designed to build any kind of web app, without spending much time on configuration or how to get data, gatsby made it easy for us.

If you have any more question feel free to ask :)

Thanks,
Mahipat :)
